### ISSUE TITLE
WeTV without subtitles will not be able to download.

### ISSUE THREAD

**Issue by seksanpuntang** [jaysonlong/webvideo-downloader#10]
Episode with subtitles can be downloaded.
https://wetv.vip/th/play/anviyiymhgufaf5
![001](https://user-images.githubusercontent.com/57736640/94434079-70580800-01c3-11eb-9b6f-d9ae261193ac.png)

Same but without subtitles will not be able to download.
https://wetv.vip/th/play/e7y96etkbv4fy42
![000](https://user-images.githubusercontent.com/57736640/94434008-53bbd000-01c3-11eb-9852-b6d328321395.png)

**Comment by jaysonlong** [comment]
There's no copyright of this video in my region and I don't have a proxy server in an available region, so I don't know what happened.

![微信图片_20201012214405](https://user-images.githubusercontent.com/40359725/95753576-66aac600-0cd4-11eb-922e-0bac794c6907.jpg)

**Comment by jaysonlong** [comment]
Fixed.
