### ISSUE TITLE
[Suggestion] youku support

### ISSUE THREAD

**Issue by irabro1992** [jaysonlong/webvideo-downloader#103]
hello , can you please add support for youku ?
there are not many downloader actually working with youku vip .
please

**Comment by Forstok93** [comment]
Hello Thanks for the great software but unfortunately I can't download this video
I have VIP access And other videos I Downloading
But this one is no way to download just a fragment
https://v.youku.com/v_show/id_XNTE5ODYzMDkwOA==.html?spm=a2hbt.13141534.1_1.2

**Comment by Forstok93** [comment]
Hello again I use VPN - 
( Urban Free VPN proxy Unblocker - Best VPN) but fortunately I can't download
I try a lot of the countries but it's not working
And the second downloader writing that
Cannot download the video for juridical reasons - Download master IDM
Here is a link of the video and I have VIP : https://v.youku.com/v_show/id_XNTIwMjAxMDcyNA==.html?spm=a2hbt.13141534.1_2.3&s=dbbf54bdee9c4c5bbbd7

**Comment by jaysonlong** [comment]
youku uses DRM to encrypt their videos since two years ago, these videos must be decrypted by the browser, so it doesn't make sense to use the downloader to download them.
