### ISSUE TITLE
I need help T^T

### ISSUE THREAD

**Issue by itsweiii** [jaysonlong/webvideo-downloader#104]
I came across this by accident when I searched for a solution to download videos from WeTV. Somehow I ended up with this?
![Python](https://user-images.githubusercontent.com/91744474/135648181-00cf56e0-1c27-4a72-b8d6-033b2908202f.png)
But then I have the button to download the videos?
![02](https://user-images.githubusercontent.com/91744474/135648322-b4fb2318-6e90-4738-a21f-2660111d2094.png)
Then I found out I have to put this in "pip install -r requirements.txt" to run "python daemon.py" but I need to first enter "cd webvideo-downloader/downloader" this to start the pip install which I wasn't able to do (shown in picture 1). I do have python installed...
![03](https://user-images.githubusercontent.com/91744474/135648916-15116eb2-2a85-48e7-a5cc-07ed48a2d628.png)
HELP PLEASE T^T

**Comment by itsweiii** [comment]
When I clicked download vvideo it shows that I need to run python daemon.py

**Comment by Sparh4wk** [comment]
you need to install python and pip. Then you need to clone this repo, or unpack that webvideo-downloader-master.zip somewhere to be able to use "cd webvideo-downloader/downloader".

**Comment by itsweiii** [comment]
I see I'll try again, thanks!

**Comment by itsweiii** [comment]
I have installed python and pip, but have issues with "clone repo"? or I'll just unpack the webvideo-downloader-master.zip. Can I just use the "extract all" feature to unpack the zip file?

**Comment by Sparh4wk** [comment]
> I have installed python and pip, but have issues with "clone repo"? or I'll just unpack the webvideo-downloader-master.zip. Can I just use the "extract all" feature to unpack the zip file?

yes, u can extract all instead of clone repo as I told you before.

**Comment by itsweiii** [comment]
Thank you!!!

**Comment by itsweiii** [comment]
Soooooo I have downloaded and extract the zip file,
![02](https://user-images.githubusercontent.com/91744474/135710284-c310ac6c-1183-4f5c-af30-3ae8d86fba72.png)
but it still shows this...
![01](https://user-images.githubusercontent.com/91744474/135710306-c838cf31-abd0-4aac-9d79-9d1ebb072119.png)
Sorry for the trouble, I'm totally new at these...

**Comment by Sparh4wk** [comment]
> Soooooo I have downloaded and extract the zip file, ![02](https://user-images.githubusercontent.com/91744474/135710284-c310ac6c-1183-4f5c-af30-3ae8d86fba72.png) but it still shows this... ![01](https://user-images.githubusercontent.com/91744474/135710306-c838cf31-abd0-4aac-9d79-9d1ebb072119.png) Sorry for the trouble, I'm totally new at these...

just use cd webvideo-downloader\downloader

or you can run daemon via: python "C:\Users\Acer\Downloads\webvideo-downloader\downloader\daemon.py"

**Comment by itsweiii** [comment]
It worked, thanks!!!
