### ISSUE TITLE
iQiyi (iq.com) Support Doesn't Work

### ISSUE THREAD

**Issue by wickedfable** [jaysonlong/webvideo-downloader#106]
Hello,

I am unable to get any videos at all, including those that are freely available, from iQiyi's iq.com site. I seem to get this error whenever trying to access videos from that site: "FileNotFoundError: [Errno 2] No such file or directory: " followed by  a long string of text.

I was able to use webvideo-downloader on another supported site like BiliBili so this issues seems specific to iQiyi  and would seem to be a problem with the program and not a user issue. I am open to any suggestions though if there is some error on my part.

**Comment by Sparh4wk** [comment]
> Okay, so I was able to download from iQiyi with the previous 1.6 version. Have you guys tried the 2.0 version yet?
> 
> Also has anyone tried with VIP videos on iQiyi?

well Im using cloned repo as mentioned in readme, so dunno about version 2.0.

"git clone https://github.com/jaysonlong/webvideo-downloader.git"
