### ISSUE TITLE
python daemon.py  怎样运行

### ISSUE THREAD

**Issue by yuanchongfu** [jaysonlong/webvideo-downloader#115]
python 3.9 装好了，环境变量都好了，就不知道python daemon.py怎样运行，求大神帮忙，谢谢

**Comment by davidjames146** [comment]
> python 3.9 装好了，环境变量都好了，就不知道python daemon.py怎样运行，求大神帮忙，谢谢

You can create a bat file for run python daemon.py or use cmd by: "cd" to your extract web-video-downloader folder and use command python daemon.py for run or create bat file.

I think you use bat file is easier for you, you open your notepad and type this and save at .bat file

@echo off
python daemon.py
pause
