### ISSUE TITLE
现在都下载不了了 提示以下错误

### ISSUE THREAD

**Issue by JL-ShenHai** [jaysonlong/webvideo-downloader#12]
Listening on port 18888 for clients...

Receive: {
    "fileName": "犬夜叉：第1话_番剧_bilibili_哔哩哔哩",
    "url": "https://221-236-179-235.mcdn.bilivideo.cn:480/upgcxcode/64/59/126445
964/126445964_nb2-1-30280.m4s?expires=1601805686&platform=pc&ssig=ZltCyaVb5GNpw5
P5AWlXDQ&oi=1946701278&trid=2f0fbc3a5d3d4a1aaec2e1383adc32b1p&nfc=1&nfb=maPYqpoe
l5MI3qOUX6YpRA==&mcdnid=1001039&mid=13872689&orderid=0,3&agrr=1&logo=A0000001|ht
tps://upos-sz-mirrorcos.bilivideo.com/upgcxcode/64/59/126445964/126445964_da2-1-
30112.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0Mv
Xg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNv
NC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1601805686&ge
n=playurl&os=cosbv&oi=1946701278&trid=2f0fbc3a5d3d4a1aaec2e1383adc32b1p&platform
=pc&upsig=0c6736f9b12db86ac8e66cb41b7413de&uparams=e,uipk,nbs,deadline,gen,os,oi
,trid,platform&mid=13872689&orderid=0,3&agrr=1&logo=80000000",
    "type": "link"
}

Handle: {
    "fileName": "犬夜叉：第1话_番剧_bilibili_哔哩哔哩",
    "url": "https://221-236-179-235.mcdn.bilivideo.cn:480/upgcxcode/64/59/126445
964/126445964_nb2-1-30280.m4s?expires=1601805686&platform=pc&ssig=ZltCyaVb5GNpw5
P5AWlXDQ&oi=1946701278&trid=2f0fbc3a5d3d4a1aaec2e1383adc32b1p&nfc=1&nfb=maPYqpoe
l5MI3qOUX6YpRA==&mcdnid=1001039&mid=13872689&orderid=0,3&agrr=1&logo=A0000001|ht
tps://upos-sz-mirrorcos.bilivideo.com/upgcxcode/64/59/126445964/126445964_da2-1-
30112.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0Mv
Xg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNv
NC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1601805686&ge
n=playurl&os=cosbv&oi=1946701278&trid=2f0fbc3a5d3d4a1aaec2e1383adc32b1p&platform
=pc&upsig=0c6736f9b12db86ac8e66cb41b7413de&uparams=e,uipk,nbs,deadline,gen,os,oi
,trid,platform&mid=13872689&orderid=0,3&agrr=1&logo=80000000",
    "type": "link"
}

--------------------------------------------------------------------------------
--------------------
Traceback (most recent call last):
  File "D:\webvideo-downloader-jaysonlong\webvideo-downlo
ader-1.6\webvideo-downloader-1.6\downloader\dispatcher.py", line 160, in dispatc
h
    linksurl, fileName = task['linksurl'], task['fileName']
KeyError: 'linksurl'
--------------------------------------------------------------------------------
--------------------

**Comment by jaysonlong** [comment]
新版本不兼容旧版，git clone 更新 python 脚本即可

**Comment by JL-ShenHai** [comment]
谢谢大大的回答

**Comment by JL-ShenHai** [comment]
大大 不知道为什么更新了 脚本 还是这个提示

**Comment by jaysonlong** [comment]
上面说错了更新是用 git pull，不管怎样只要你更新了最新版本就不会报错

**Comment by JL-ShenHai** [comment]
好 我再试试

**Comment by JL-ShenHai** [comment]
大大我直接把你的仓下载用 也有问题 不知道为啥
