### ISSUE TITLE
爱奇艺视频无法下载

### ISSUE THREAD

**Issue by jing207** [jaysonlong/webvideo-downloader#134]
这是什么原因，是python 版本不支持吗  3.9版本
![image](https://user-images.githubusercontent.com/77466712/173222915-d251a415-4496-4af2-b0f4-5d2c5da8b7cb.png)

**Comment by peedan** [comment]
No problem for Iqiyi, that's your own problem.

**Comment by jaysonlong** [comment]
我这边没有问题
