### ISSUE TITLE
wetv下载字幕不显示，腾讯视频界面不显示下载按钮

### ISSUE THREAD

**Issue by artemisluck97** [jaysonlong/webvideo-downloader#135]
麻烦大佬修复啦~~辛苦辛苦

**Comment by jaysonlong** [comment]
腾讯视频已修复

**Comment by peedan** [comment]
> 腾讯视频已修复

Wetv still cannot work, only video but no subtitles. Would you please fix it? Thanks a lot. @jaysonlong

**Comment by jaysonlong** [comment]
> > 腾讯视频已修复
> 
> Wetv still cannot work, only video but no subtitles. Would you please fix it? Thanks a lot. @jaysonlong

WETV字幕问题已修复
