### ISSUE TITLE
請問騰訊現在是否無法下載了？藍色圓圈已經出不來了～愛奇藝是可以的

### ISSUE THREAD

**Issue by charles0568** [jaysonlong/webvideo-downloader#136]
請問騰訊現在是否無法下載了？藍色圓圈已經出不來了～愛奇藝是可以的

**Comment by charles0568** [comment]
看來是沒機會修復了～還是謝謝作者的辛勞～感謝你！

**Comment by jaysonlong** [comment]
已经修复

**Comment by charles0568** [comment]
太感謝作者了！！！謝謝！！！

**Comment by opennewworld58** [comment]
请问那个ffmpeg路径应该怎样弄呢？我的总是合并出来后videos是空的

**Comment by opennewworld58** [comment]
Windows系统

**Comment by opennewworld58** [comment]
Windows10

**Comment by 4ft35t** [comment]
同样问题，爱奇艺出篮圈，腾讯视频不出。

**Comment by 4ft35t** [comment]
> 同样问题，爱奇艺出蓝圈，腾讯视频不出。

已找到原因

congole 里看到 `https://vd6.l.qq.com/proxyhttp` 访问报错，域名不能解析；检查了下，路由器上订阅的广告过滤名单把域名拉黑了，解除后蓝圈正常出现。
