### ISSUE TITLE
macOS视频下载到了什么地方？webvideo-downloader-1.6目录下没有

### ISSUE THREAD

**Issue by huronzhu** [jaysonlong/webvideo-downloader#14]
macOS视频下载到了什么地方？webvideo-downloader-1.6目录下没有

**Comment by jaysonlong** [comment]
在项目目录下的 videos 文件夹

**Comment by huronzhu** [comment]
看过是空的

**Comment by huronzhu** [comment]
> 在项目目录下的 videos 文件夹

看过是空的

**Comment by jaysonlong** [comment]
在 downloader/config.py 里可以配置下载路径，你试试写绝对路径，之前好像有人说过 macOS python 3.7 不支持相对路径。还可以运行 python daemon.py -d 打印更详细的信息来排错。
