### ISSUE TITLE
哪里可以修改http://cache-video.iq.com/xxxxx....  这个链接的值？

### ISSUE THREAD

**Issue by chopper-go** [jaysonlong/webvideo-downloader#17]
这个链接里的bid是清晰度，网页播放时最高只有1080p，要是能增加修改这个字段的功能，就能支持4k了。
如果你不方便修改的话，能否告知修改方法？我尝试了几次，没成功。
需要会员账号或其他信息，欢迎来邮 reg163001@163.com

**Comment by jaysonlong** [comment]
**理想很美好，现实很骨感。**

且不说爱奇艺是否有开放通过 web 请求获取 4k 画质视频，就算有开放，url 中的某些参数也是由前端 js 代码生成用来做身份校验的，要想手动构造参数，只能老老实实地啃前端代码，这将是一个冗长又繁琐的过程。

**Comment by lzkgbld** [comment]
你可以尝试自己看视频的时候设置为4K画质，然后把地址丢给下载脚本尝试下载，作者之所以用脚本去抓这个地址，就是用户能看到什么，他的脚本就能下载到什么...

**Comment by chopper-go** [comment]
国内爱奇艺是支持的。参考 https://zhuanlan.zhihu.com/p/97844384 ，也是配合chrome浏览器，通过 web 请求获取 4k 画质，他的代码支持修改bid参数 ，不过这个限国内爱奇艺。
