### ISSUE TITLE
請問爱奇艺國際為什麼下載會出現這東西?

### ISSUE THREAD

**Issue by cokebb** [jaysonlong/webvideo-downloader#18]
![QQ图片20201018150611](https://user-images.githubusercontent.com/73053501/96360877-9a15a680-1153-11eb-8fb9-76c7c0f2cded.png)
  
新手一名~~~怎麼解決這問題?

**Comment by David-H-1** [comment]
答案就如圖所示，你沒有在windows命令提示符或mac/linux終端中運行python daemon.py

**Comment by David-H-1** [comment]
特別注意！得先 運行pip install requests colorama
才能運行daemon.py

**Comment by cokebb** [comment]
好的~~謝謝~~現在可以了~~
