### ISSUE TITLE
 字幕顯示不正常，貌似愛奇藝國際站對字幕進行了base64編碼

### ISSUE THREAD

**Issue by David-H-1** [jaysonlong/webvideo-downloader#19]
![image](https://user-images.githubusercontent.com/60801469/96520067-1a570d00-1223-11eb-83f8-9a630209c0f2.png)
如圖所示，字幕是經過編碼過的，而不是明文字符（漢字，英文） 
經過我初步判斷，應該是base64編碼

**Comment by David-H-1** [comment]
@jaysonlong

**Comment by David-H-1** [comment]
我確定我的播放器沒有問題

**Comment by David-H-1** [comment]
十个字幕沒一个是明文

**Comment by jaysonlong** [comment]
请给出问题视频地址

**Comment by David-H-1** [comment]
iq.com/play/vfyzd2n62wOn Mon, Oct 19, 2020 at 6:23 PM, Jayson <notifications@github.com> wrote:  
请给出问题视频地址

**Comment by jaysonlong** [comment]
不是 base64，这里是使用 C++ 编写的 WebAssembly 形式的自定义编解码器。目前还没找到什么在浏览器之外如python脚本中解码的办法。

目前的解决方案是通过以下代码伪装当前浏览器的 WebAssembly 兼容性：
```javascript
window.WebAssembly = undefined;
```
这样可以直接获取明文字幕，绕过自定义编码。
暴力猴脚本已更新： fe8ed01975992ad1786859b24849342cb9d45bc0

**Comment by David-H-1** [comment]
請問我用的Tampermonkey也行嗎？On Mon, Oct 19, 2020 at 11:16 PM, Jayson <notifications@github.com> wrote:  
不是 base64，这里是使用 C++ 编写的 WebAssembly 形式的自定义编解码器。目前还没找到什么在浏览器之外如python脚本中解码的办法。
目前的解决方案是通过以下代码伪装当前浏览器的 WebAssembly 兼容性：
window.WebAssembly = undefined;
这样可以直接获取明文字幕，绕过自定义编码。
暴力猴脚本已更新： fe8ed01

**Comment by jaysonlong** [comment]
能自己试出答案的就不要问了

**Comment by David-H-1** [comment]
謝謝大佬，現在顯示正常了
