### ISSUE TITLE
AdGuard客户端无法安装

### ISSUE THREAD

**Issue by xiaohaozhi** [jaysonlong/webvideo-downloader#2]
用的win版，直接报错了

**Comment by jaysonlong** [comment]
我不是 AdGuard 开发者，也没用过桌面版，只用过插件版本，另外广告拦截不是必须的。

**Comment by xiaohaozhi** [comment]
这个脚本并不与AdGuard兼容，
介绍页面上写着“AdGuard 广告拦截器（推荐安装）”
我以为是用这个软件加载脚本是可以完美兼容的。

可能您这么写只是用这个软件拦截下广告。。。。φ(￣ー￣ )ノ

**Comment by jaysonlong** [comment]
脚本在网站加载真实视频资源时才会进行解析，使用拦截器可以让网站直接加载视频资源而无需等待广告时间。以**芒果TV**为例，如果不拦截需要等待广告播放一段时间才会加载视频资源；但有的网站视频资源是预加载的（和广告同时加载），这类网站拦不拦截都可以秒解析。脚本和 AdGuard 一点关系没有，只不过广告拦截器**或许**可以使视频资源的解析提前。
