### ISSUE TITLE
打不开daemon.py

### ISSUE THREAD

**Issue by chali26** [jaysonlong/webvideo-downloader#26]
我下了压缩包然后还下了3.9版本的python 但是我双击上面这个文件就一直在闪退，从网站点进去就一直写 “请先运行 python daemon.py” 我百度了但是也没有解决这个问题 不知道是我下的py版本有问题还是那出现问题了

**Comment by jaysonlong** [comment]
#6 
#24

**Comment by chali26** [comment]
> [＃6 ](https://github.com/jaysonlong/webvideo-downloader/issues/6)
> [＃24](https://github.com/jaysonlong/webvideo-downloader/issues/24)

可以用了 谢谢 但是芒果tv 405错误 别的都可以用
