### ISSUE TITLE
愛奇藝台灣站VIP視頻下載不了

### ISSUE THREAD

**Issue by ookay0018948** [jaysonlong/webvideo-downloader#28]
"已經是VIP會員"

https://tw.iqiyi.com/v_1686465av2o.html

前五集不須VIP可以觀看 (可以正常下載)
後兩集需VIP才可觀看 (下載顯示http响应: 405错误)

其他劇集需要VIP才可觀看的集數 下載也提示同樣錯誤

**Comment by jaysonlong** [comment]
我没有 VIP 账号无法调试修复。如果你想要解决，请将可用的 VIP 账号密码发至我的邮箱: im.lgchen@foxmail.com
