### ISSUE TITLE
Issues with no Subtitles

### ISSUE THREAD

**Issue by Angu0083** [jaysonlong/webvideo-downloader#30]
Hello, 

       The latest update scripts couldn't download the subtitles, and I know these scripts won't support to download the subtitles.

       I love Chinese drama, But without subtitles difficult to understand the conversion. I don't know the Chinese language.

       Kindly re-update the script to prompt the subtitle option for optionally.

**Comment by jaysonlong** [comment]
**Did you update the browser violentmonkey script?** 

My project now can download both the videos with and without subtitles, that means if you can see the subtitles online in the browser, the video you download will also contain subtitles.

Of course if there's no subtitle in some online video, I can't create it out of thin air😂. 

In this situation, you can try to find another video resource whose content is the same. Such as the two videos below, they one contains subtitle while another doesn't:
- https://wetv.vip/en/play/4cpllzcg2i3hn1a/o0030o7shei
- https://wetv.vip/en/play/inlpm3b3j6xbedt/c0033c2xg9c
