### ISSUE TITLE
下载爱奇艺国际站视频出现问题

### ISSUE THREAD

**Issue by chali26** [jaysonlong/webvideo-downloader#32]
![Snipaste_2020-11-16_15-44-50](https://user-images.githubusercontent.com/73935991/99225576-3ac6b700-2823-11eb-96dd-4aacb9224f27.png)
如图 不知道怎么办 看不懂

**Comment by jaysonlong** [comment]
我在国际站找不到这个视频

**Comment by chali26** [comment]
https://www.iq.com/play/m0ehrce4bw?frmrp=search&frmb=list&frmrs=fenji_button
链接在这 我用的香港线路

**Comment by jaysonlong** [comment]
需要用命令行代理(http_proxy&https_proxy)。需要代理才能在线看的视频，也要用代理才能下载。

**Comment by chali26** [comment]
额 你说的我看不懂欸 你能直接告诉我怎么解决吗 代理是啥

**Comment by jaysonlong** [comment]
代理就是线路，你用的什么软件的线路

**Comment by chali26** [comment]
然后呢 代码哪里我要怎么改啊改什么 为啥我之前下都可以

**Comment by jaysonlong** [comment]
我问你用的什么软件的线路

**Comment by chali26** [comment]
ssr的 线路是指复制的链接吗

**Comment by jaysonlong** [comment]
如果是用ssr的线路，就先执行命令：
```
set http_proxy=socks5://127.0.0.1:1080
set https_proxy=socks5://127.0.0.1:1080
```
再执行daemon.py
