### ISSUE TITLE
下爱奇艺国际版时提示ProxyError

### ISSUE THREAD

**Issue by jfan0920** [jaysonlong/webvideo-downloader#37]
我下这个链接https://www.iq.com/play/19rwv92hp8，泰国线的，就一直是代理错误下不了
requests.exceptions.ProxyError: HTTPSConnectionPool(host='cache-video.iq.com', port=443): Max retries exceeded with url: 略 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out')))
请问要如何解决呀？
我开着plex加速器

**Comment by ali617768987** [comment]
亲故 你的问题解决了吗  我也是这个问题 要vpn的都下不了~

**Comment by jaysonlong** [comment]
我这边没问题。
加速器关了试试，进入页面后关掉加速器再点下载。
