### ISSUE TITLE
macOS无法使用ffmpeg转换视频格式

### ISSUE THREAD

**Issue by xiebruce** [jaysonlong/webvideo-downloader#39]
![image](https://user-images.githubusercontent.com/13575500/102077477-56ce7000-3e44-11eb-8a72-a3aacb181812.png)

是不是没有转换格式功能？下载的视频很多时候没有mp4但希望能转换成mp4

**Comment by jaysonlong** [comment]
不提供，想转换自己百度 ffmpeg 的用法

**Comment by xiebruce** [comment]
好吧，其实我也不是不会，就是觉得能转就不用自己手动去转，不过后来想想，如果要在下载后转换，会导致下载速度很慢(如果把转换也当作下载过程的话)，所以我还是自己下载好批量转换了。

**Comment by jaysonlong** [comment]
如果是mp4格式兼容的编码比如f4v的h264+aac，使用-c copy转格式也就几秒钟的事情，否则需要重新编码耗时很长。下载完成合并后自己转换格式和视频合并时就转换的耗时是一样的，都要重新编码（如果不兼容）或都不用重新编码（如果兼容）。我这里不更改容器格式直接合并视频，保证了合并速度和和视频的可用性（指定转码为固定格式可能出错）。

**Comment by xiebruce** [comment]
> 如果是mp4格式兼容的编码比如f4v的h264+aac，使用-c copy转格式也就几秒钟的事情，否则需要重新编码耗时很长。下载完成合并后自己转换格式和视频合并时就转换的耗时是一样的，都要重新编码（如果不兼容）或都不用重新编码（如果兼容）。我这里不更改容器格式直接合并视频，保证了合并速度和和视频的可用性（指定转码为固定格式可能出错）。

嗯，确实
