### ISSUE TITLE
请求添加台湾爱奇艺和WETV进去，大神

### ISSUE THREAD

**Issue by bugushe** [jaysonlong/webvideo-downloader#4]

**Comment by bugushe** [comment]
请求添加台湾爱奇艺和WETV进去，大神

**Comment by jaysonlong** [comment]
可以，有时间看看

**Comment by bugushe** [comment]
> 可以，有时间看看

感谢大神，希望能早点看到

**Comment by jaysonlong** [comment]
WeTV： 29f902c939d81afa06d60f6bd462e7ff2feb0689
愛奇藝台灣站： cf360b557d2a4583f5cd7f5d5d7977770cfe1208
