### ISSUE TITLE
请先运行 "python daemon.py"

### ISSUE THREAD

**Issue by karenyen09** [jaysonlong/webvideo-downloader#40]
Thanks for your application. I'm really like it
I have no knowledge about IT so in the step install daemon.py, I don't know how to install ans run it. Can you instruct me or record an instruction video? Thanks so much.

**Comment by karenyen09** [comment]
![Ảnh chụp màn hình (111)](https://user-images.githubusercontent.com/51255591/102779570-0cf70400-43c7-11eb-8da9-bb0e9b7be561.png)
How can I solve this problem?

**Comment by jaysonlong** [comment]
Run the command below to install dependencies (only once for the first time):
```
pip install -r requirements.txt
```
And then re run the command `python daemon.py`, and click the download btn in the browser, it will works.

**Comment by karenyen09** [comment]
Thanks, it finally works. I still have a question about subtitiles. I want to download a Wetv video. On the web there are more than 5 sub, but when downloded it just have 2 sub. This is the link:https://wetv.vip/en/play/6b2ol4xx6ttgen3-Cherry-Magic!-Thirty-Years-of-Virginity-Can-Make-You-a-Wizard%3F!/g0035j24ybm-EP1--Cherry-Magic!-Thirty-Years-of-Virginity-Can-Make-You-a-Wizard%3F!?vid=g0035j24ybm

**Comment by azraki** [comment]
> Run the command below to install dependencies (only once for the first time):
> 
> ```
> pip install -r requirements.txt
> ```
> 
> And then re run the command `python daemon.py`, and click the download btn in the browser, it will works.

Can you help me how to install dependencies?

**Comment by jaysonlong** [comment]
@karenyen09  It seems that there's no copyright of this [video](https://wetv.vip/en/play/6b2ol4xx6ttgen3-Cherry-Magic!-Thirty-Years-of-Virginity-Can-Make-You-a-Wizard%3F!/g0035j24ybm-EP1--Cherry-Magic!-Thirty-Years-of-Virginity-Can-Make-You-a-Wizard%3F!?vid=g0035j24ybm) in my region.
> Sorry, we don’t have the copy right of this content in your region yet. We will fight this for you on our greatest effort!
