### ISSUE TITLE
MangoTV download

### ISSUE THREAD

**Issue by karenyen09** [jaysonlong/webvideo-downloader#41]
Hi, when I try to download video from MangoTV, it does't appear the place for choosing the download option. Can you check this site?
![image](https://user-images.githubusercontent.com/51255591/102903697-469d3d00-44a3-11eb-9038-8028a10bcbab.png)

**Comment by azraki** [comment]
> Hi, when I try to download video from MangoTV, it does't appear the place for choosing the download option. Can you check this site?
> ![image](https://user-images.githubusercontent.com/51255591/102903697-469d3d00-44a3-11eb-9038-8028a10bcbab.png)

How to run daemon.py?

**Comment by jaysonlong** [comment]
@karenyen09 The chrome updated recently, you should update the violentmonkey scripts and try again.

**Comment by azraki** [comment]
> @karenyen09 The chrome updated recently, you should update the violentmonkey scripts and try again.

How can I prevent the subtitles from being picked up when shooting the video?

**Comment by jaysonlong** [comment]
I don't understand what you are saying.
