### ISSUE TITLE
tengxun downloaded video seems to be a little jittery

### ISSUE THREAD

**Issue by Ziggareto** [jaysonlong/webvideo-downloader#43]
Hi thanks for the great work.

I downloaded a ~20 minute video from v.qq.com, it's mostly great but there are a few little jumps / ticks which I feel might be from incorrect joining of small segments. The downloaded video has length 22:37 whereas the original is 22:19, which is odd. I wonder if you have any ideas if this is possible to fix?

Thanks

**Comment by jaysonlong** [comment]
This project has been updated, run the command below to force to correct the timestamp of the hls videos.
```console
$ git pull
$ python daemon.py --correct
```
I'm not sure that all videos can play normally as before after correcting, to correct or not, that's up to you.

**Comment by Ziggareto** [comment]
Thanks so much it's working well!
