### ISSUE TITLE
集成字幕不保存为MP4

### ISSUE THREAD

**Issue by kongbaiwww** [jaysonlong/webvideo-downloader#45]
如何修改 集成字幕 成MKV格式，或者不进行合并，因为要修改字幕文件的
是修改这一段吗 麻烦给指点一下
def integrateSubtitles(subtitlesInfo, videoName):
    print('正在集成字幕')

    subtitleNames = list(map(lambda x: x[1], subtitlesInfo))
    fileNames = [videoName] + subtitleNames
    inputCmd = ' '.join(map(lambda x: ('-i "%s"' % x), fileNames))
    mapCmd = '-map 0'
    for i, (name, subtitleName) in enumerate(subtitlesInfo):
        mapCmd += ' -map %d -metadata:s:s:%d title="%s"' % (i+1, i, name)

    isMp4 = videoName.endswith('.mp4')
    tempVideoName = videoName.rsplit('.', 1)[0] + '.srt.mp4'
    targetFileName = videoName if isMp4 else (videoName.rsplit('.', 1)[0] + '.mp4')
    logLevel = 'info' if debug else 'fatal'

**Comment by jaysonlong** [comment]
```
python daemon -d
```
会保留所有临时文件
