### ISSUE TITLE
Issues on MacBook Air M1 

### ISSUE THREAD

**Issue by maradonaz** [jaysonlong/webvideo-downloader#47]
I got everything installed except when I try to execute daemon.py in terminal I get this error.

<img width="579" alt="Screen Shot 2020-12-26 at 2 08 25 PM" src="https://user-images.githubusercontent.com/76628264/103157718-0af4c280-4784-11eb-8a02-ed6a188f5d87.png">

Is it possible for you to do a step by step for Mac users.

**Comment by jaysonlong** [comment]
Use python >= 3.5, run `python --version` to confirm. 
Run `python3 daemon.py` if you have installed both python2 and python3.

**Comment by maradonaz** [comment]
Thank you got it working. The pip install manager wasn't installed properly
