### ISSUE TITLE
iq.com support 

### ISSUE THREAD

**Issue by ever-lae** [jaysonlong/webvideo-downloader#5]
Hello, would it be possible to add support for iQiyi videos on iq.com? Thanks a lot.

**Comment by jaysonlong** [comment]
Busy working recently, may be added later

**Comment by jaysonlong** [comment]
bb4e392a534c2769a722ae60b449510fc98e733c

Supported, you can update the violentmonkey script and python script

**Comment by ever-lae** [comment]
Thank you so much, you are the greatest of all time 大神
