### ISSUE TITLE
要用vpn看的比如台湾爱奇艺 跟国际版的爱奇艺都下载不了

### ISSUE THREAD

**Issue by ali617768987** [jaysonlong/webvideo-downloader#52]
你好 感谢分享这么棒的软件 

想问一下 就是要用vpn看的比如台湾爱奇艺 下载的时候都是现实错误下载不了

但是不使用代理的都可以，这是怎么情况呢？

**Comment by kongbaiwww** [comment]
你虽然开了VPN但线路依然是本地，vpn必须用全局的才可以

**Comment by ali617768987** [comment]
> 你虽然开了VPN但线路依然是本地，vpn必须用全局的才可以

我开了全局的 都没有 都试过了不知道怎么回事~

**Comment by ali617768987** [comment]
> 你虽然开了VPN但线路依然是本地，vpn必须用全局的才可以

你如果可以下的话 求教一下 呜呜呜 我真的无望了 有的电视剧只有挂vpn才看得到

**Comment by ali617768987** [comment]
是要设置什么吗 我小火箭跟clash都用过了开了全局  下载国际版或者台湾版的iqiyi都是显示错误time out  但是不要开代理的国际版都可以正常下载 所以有点懵了~~~求指教~~

**Comment by jaysonlong** [comment]
如果使用Shadowsocks(R)，Windows系统依次执行：
```
set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
python daemon.py
```

**Comment by ali617768987** [comment]
> 如果使用Shadowsocks(R)，Windows系统依次执行：
> 
> ```
> set http_proxy=http://127.0.0.1:1080
> set https_proxy=http://127.0.0.1:1080
> python daemon.py
> ```

![微信截图_20210122011936](https://user-images.githubusercontent.com/77323405/105388004-1509c400-5c51-11eb-9541-bf8ab3c10343.png)
![微信截图_20210122012530](https://user-images.githubusercontent.com/77323405/105388018-189d4b00-5c51-11eb-815d-36de4fb3a72d.png)

大大  我的是win10系统 按你给的代码执行好像没有反应  一直显示time out 要怎么弄呢？

**Comment by ali617768987** [comment]
> http://127.0.0.1:1080

解决了 摸索出来了 可以下载了 谢谢大大 ~~

**Comment by azraki** [comment]
> 如果使用Shadowsocks(R)，Windows系统依次执行：
> 
> ```
> set http_proxy=http://127.0.0.1:1080
> set https_proxy=http://127.0.0.1:1080
> python daemon.py
> ```

Not work
