### ISSUE TITLE
WETV.VIP 

### ISSUE THREAD

**Issue by maradonaz** [jaysonlong/webvideo-downloader#53]
Good Day

For some videos on wet.vip the files download in the temp with the translation fine but then during the merging of files the video shows the full file size but then at the end it goes down to kb size which is not right. Is there a work around for this cause its not all videos just a specific show even though the week before I was able to download it properly.

**Comment by antonio8909** [comment]
I'm having the same issue with Ep.2 of No.1 For You 
https://wetv.vip/en/play/dy0tqsfvpl73f7f-No.1-For-You/h0035rh3y6s-EP2--No.1-For-You

**Comment by maradonaz** [comment]
That actually the show I'm having issues with also.

**Comment by anfa14** [comment]
i'm having same issue, please i beg you

**Comment by gekkoheart** [comment]
WeTV seems to have implemented SAMPLE-AES encryption and Widevine into the hls stream. So, basically, the downloader is downloading the files just fine but when it sends the files to ffmpeg to put them together, the file becomes corrupt because the fragments are all encrypted.

**Comment by antonio8909** [comment]
I hope a fix will come soon

**Comment by maradonaz** [comment]
Hope they do figure it out soon before the other shows are affected.

**Comment by maradonaz** [comment]
It seems to be working now

**Comment by anfa14** [comment]
it working now idk what happen
