### ISSUE TITLE
下载爱奇艺VIP视频失败

### ISSUE THREAD

**Issue by stanley43124725** [jaysonlong/webvideo-downloader#56]
https://www.iq.com/play/1euk1nkryqo
![785](https://user-images.githubusercontent.com/65820113/105435311-18746e00-5c98-11eb-888c-f56dac7b0e0d.JPG)
国际站及台湾站都会报错 限定VIP视频
似乎是爱奇艺有些许调整

**Comment by ali617768987** [comment]
没出现这个情况 可能是他们服务器刚刚上架视频 有调整  你重新再下一次就可以了~

**Comment by stanley43124725** [comment]
试了一次 还是不行 就只有这部的VIP不行 很奇怪

**Comment by azraki** [comment]
![Error](https://user-images.githubusercontent.com/43163065/105615259-1eb53800-5dc7-11eb-9587-cb03a3efb0d8.JPG)
和我一样

**Comment by ali617768987** [comment]
我试了下载你发的那个 动漫 可以下呀~ 
![微信截图_20210124104241](https://user-images.githubusercontent.com/77323405/105619796-011cb880-5e31-11eb-88c4-3fa326e38818.png)

我最近发现不能下的情况 是 他们刚刚上架的时候 然后聚集列表会有调整的时候 那个时候下不了 我试过很多次 但是过几分钟 调整好了 又可以下载了~~

**Comment by snowywish** [comment]
same error pls help me
