### ISSUE TITLE
能否直接调用ffmpeg -i "url" -c copy 来下载hls流

### ISSUE THREAD

**Issue by sbw983** [jaysonlong/webvideo-downloader#61]
RT 
这样下hls流就不需要保存临时文件了，我手动解析了m3u8文件就是怎么下载的，速度贼快

BTW   ：能否支持socks5代理？

**Comment by jaysonlong** [comment]
如果m3u8里所有url都包含全域名，并且没有加密和请求头校验，当然可以直接调用下载。
