### ISSUE TITLE
Subtitles are not included with video files.

### ISSUE THREAD

**Issue by kkea08** [jaysonlong/webvideo-downloader#62]
![1615389078118](https://user-images.githubusercontent.com/79582593/110654192-80ebc000-81f0-11eb-8c81-ba9f43f65d4e.jpg)

When I load the video, there is no subtitle.

**Comment by jaysonlong** [comment]
Show me the download page url, if you logged in or not, if is vip or not, and which region you based.

**Comment by kkea08** [comment]
อุ่นไอในใจเธอ (wetv.vip) <https://wetv.vip/play/4cpllzcg2i3hn1a/v00309b52wy>

I'm logged in and I'm a VIP. Other episodes I can load normally. But I
can't load.episode  4.

[image: image.png]


ในวันที่ อา. 23 พ.ค. 2021 เวลา 22:10 Jayson ***@***.***>
เขียนว่า:

**Comment by jaysonlong** [comment]
Fixed: b9576756276628a0b0833e65833dac8a8b57f920
You should update the python scripts to solve it.

**Comment by kkea08** [comment]
I upgraded to Python 3.9.6 but still can't.
If not, that's fine.
thank you for the advice 😀

[image: image.png]

ในวันที่ ส. 24 ก.ค. 2021 เวลา 00:11 Jayson ***@***.***>
เขียนว่า:

**Comment by jaysonlong** [comment]
Long ago issue, try open a new issue if it still exists now

**Comment by kkea08** [comment]
The problem has been fixed.
Thank you

ในวันที่ พ. 8 ก.พ. 2023 เวลา 10:16 Jayson ***@***.***>
เขียนว่า:
