### ISSUE TITLE
WebVideoDownloader.user.js 破坏了 B 站视频页

### ISSUE THREAD

**Issue by Skimige** [jaysonlong/webvideo-downloader#64]
B 站相关插件 / 脚本较多，测试了一下，单独禁用此脚本就正常了。
开启脚本会导致右上角和评论区等无法加载。

**Comment by barnett2010** [comment]
我也遇到了这个bug。搜索框也不显示 。所以会临时关掉脚本

**Comment by jaysonlong** [comment]
已修复 49311aa71e88db887b39edbc017eecde5267f03f
