### ISSUE TITLE
无法在IQiYI上下载视频

### ISSUE THREAD

**Issue by azraki** [jaysonlong/webvideo-downloader#68]
我想在IQiYi网站上下载其中一个动画，但是我必须使用VPN来访问它，但是当我要下载时，看到代理错误。 请找到解决方案。
![IMG_20210319_043610_HDR](https://user-images.githubusercontent.com/43163065/111694300-ade14800-886c-11eb-802f-6ceeb2e262c4.jpg)

**Comment by jaysonlong** [comment]
请给出下载地址，是否已登录，是否VIP，VPN软件名称，VPN代理地区
