### ISSUE TITLE
youku 1080p下载失败

### ISSUE THREAD

**Issue by W-Leviosa** [jaysonlong/webvideo-downloader#69]
登陆了会员之后下载
结果是一个258bytes的打不开的mp4文件

edit:重新测试了一下 比较短的视频没问题 半小时以上的综艺不行

**Comment by ali617768987** [comment]
亲 看简介 没有说支持优酷呀 当然下载失败啦

**Comment by jaysonlong** [comment]
使用DRM版权保护的视频都不支持下载，优酷大部分视频都有DRM保护
