### ISSUE TITLE
腾讯视频不显示下载按钮

### ISSUE THREAD

**Issue by xmhwws** [jaysonlong/webvideo-downloader#7]
链接：https://v.qq.com/x/page/x31502rr0cv.html
![image](https://user-images.githubusercontent.com/42903751/93009230-ce280580-f5b0-11ea-828e-7ee0bf2fb120.png)

**Comment by jaysonlong** [comment]
ad5ba84c6bbf89cafcab4560eb9aee10546c57b8 更新了

**Comment by xmhwws** [comment]
反馈一个情况，不知道是不是bug：
以上面发的链接，蓝光格式为例，每一段一开始下载速度几MB/S，到每一段后面时，速度降到几十KB/S
![2020-09-14_00-31-54_2](https://user-images.githubusercontent.com/42903751/93045699-6fcf5580-f68a-11ea-9b01-311adf899120.png)


这样，下载一个视频速度就很慢

2.昨天晚上可以下载，今天再下载就报SSL错误
![2020-09-14_12-54-29](https://user-images.githubusercontent.com/42903751/93045519-fcc5df00-f689-11ea-8243-3896d2e6e296.png)

**Comment by jaysonlong** [comment]
1. 多线程下载到最后较快的线程都完成之后，只剩1-2个慢速线程在继续下载，速度变慢，另外某些服务器也会对连接最后的部分字节流进行限速。网络足够顺畅时（低延迟，高带宽）不会出现这个问题。
2. 这个是你的环境问题，最常见的是使用了代理，而代理进行了中间人攻击，另外某些 python 版本的 urllib 库也会出现这个 bug。

### 解决方案
1. 可使用命令行参数 `-t:f` 减少线程数，具体可根据网络情况和文件大小确定。小文件可设置单线程或少数几个线程下载。
2. 换个网络环境，或者在 requests 库发送请求时禁用 ssl 证书验证（verify=False）。

**Comment by xmhwws** [comment]
1.还是上面的链接，不知道为什么腾讯视频的下载按钮又没了，B站倒是没问题
![2020-09-19_11-35-24_2](https://user-images.githubusercontent.com/42903751/93658320-13df4500-fa6d-11ea-86e7-46498406f96c.png)
![2020-09-19_11-37-53](https://user-images.githubusercontent.com/42903751/93658270-c1058d80-fa6c-11ea-84ca-84a4ee232e8f.png)

2.下载错误解决了，是我电脑代理问题

**Comment by jaysonlong** [comment]
刷新，刷到弹出为止。

**Comment by jaysonlong** [comment]
更新优化了
