### ISSUE TITLE
愛奇藝 台灣VIP  無法下載

### ISSUE THREAD

**Issue by mlchen21456** [jaysonlong/webvideo-downloader#70]
![image](https://user-images.githubusercontent.com/68818222/112970855-39b67680-9181-11eb-89cc-2a406f128ee8.png)

**Comment by snowywish** [comment]
same here pls help someone

**Comment by YFTX2015** [comment]
爱奇艺国际版同样无法下载，只能用vvtoolbox。

**Comment by jaysonlong** [comment]
我没有台灣站和国际站的 VIP 账号，无法进行测试，如果希望解决的话，请将可用的VIP账号和密码发送到我的个人邮箱： im.lgchen@foxmail.com

**Comment by YFTX2015** [comment]
> 我没有台灣站和国际站的 VIP 账号，无法进行测试，如果希望解决的话，请将可用的VIP账号和密码发送到我的个人邮箱： [im.lgchen@foxmail.com](mailto:im.lgchen@foxmail.com)

账号密码已经邮给你了。

**Comment by jaysonlong** [comment]
> > 我没有台灣站和国际站的 VIP 账号，无法进行测试，如果希望解决的话，请将可用的VIP账号和密码发送到我的个人邮箱： [im.lgchen@foxmail.com](mailto:im.lgchen@foxmail.com)
> 
> 账号密码已经邮给你了。

没有收到账号，请确认是否已发送

**Comment by YFTX2015** [comment]
> > > 我没有台灣站和国际站的 VIP 账号，无法进行测试，如果希望解决的话，请将可用的VIP账号和密码发送到我的个人邮箱： [im.lgchen@foxmail.com](mailto:im.lgchen@foxmail.com)
> > 
> > 
> > 账号密码已经邮给你了。
> 
> 没有收到账号，请确认是否已发送

再看看，这次应该成功了

**Comment by YFTX2015** [comment]
@jaysonlong 收到账号没？台湾爱奇艺vip视频得行不？

**Comment by jaysonlong** [comment]
还没有时间去看

**Comment by jaysonlong** [comment]
我这边下载没有问题，请详细说明哪个视频、出现什么问题

**Comment by YFTX2015** [comment]
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/120222553-b265ac00-c272-11eb-973d-7582c234bf77.png)
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/120222558-b396d900-c272-11eb-8dce-e649bdf3e6e8.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/120222560-b42f6f80-c272-11eb-9bbc-b71ddb4fbec0.png)
![屏幕截图(4)](https://user-images.githubusercontent.com/12757305/120222561-b4c80600-c272-11eb-8efa-328904179d5e.png)
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/120222565-b5609c80-c272-11eb-8a5e-b605a69ced85.png)
![屏幕截图(6)](https://user-images.githubusercontent.com/12757305/120222566-b5f93300-c272-11eb-967c-3f2515daa340.png)
我这边所有的爱奇艺国际台湾版动画番剧1080P下载界面都是这样。系统：win10 build 21390, 代理工具：v2rayn, 机场节点：日不落机场台湾上海电信线路，台湾广州移动线路

**Comment by YFTX2015** [comment]
下载器又重新下载了，两个脚本也重新安装了，用所有支持油猴子的浏览器又试了，还是跟以前一样的下载错误，跟其他人遇到的情况都一样，不晓得你那边测试怎么会成功。

**Comment by monyau** [comment]
亲爱的jaysonlong:

您好! 很抱歉打扰麻烦您了!

爱奇艺台湾站tw.iqiyi.com已经改变了，所以webvideo-downloader这个脚本不能再下载爱奇艺台湾站的视频了。
恳请亲修改脚本哦。
万分谢谢您!

https://www.iq.com/play/coffee-friends-19rrhw2j41?frmrp=search&frmb=list&frmrs=title

**Comment by jaysonlong** [comment]
@monyau 最新的脚本已经修复支持了

**Comment by monyau** [comment]
亲:

谢谢您超快回复!

已经重新安装了violentmonkey->WebVideoDownloader 脚本 + CommonHlsDownloader 脚本
也重新下载了 all Codes
重新启动我的PC

采用firefox登录
https://www.iq.com/play/coffee-friends-19rrhw2j41?frmrp=search&frmb=list&frmrs=title
violentmonkey is active

我的操作系统是ubuntu 21.04
i run codes in terminal as below:
cd webvideo-downloader/downloader
pip install -r requirements.txt
python3 daemon.py

terminal output:
*Listening on port 18888 for clients...*

firefox没有下载图标

我不知道我错了什么。两周前还可以下载的。
恳请亲指导!

monyau2上

**Comment by jaysonlong** [comment]
@monyau I don't have this problem. It happened on some or any video?

**Comment by monyau** [comment]
亲，

我我已经两次重新下载webvideo-downloader-master.zip, unzip和 安装了你的codes , 但还是无法下载任何  E1~E10 一集的720p“咖啡朋友”。 
我不知道我犯了什么错误。 :-(
