### ISSUE TITLE
[Suggestion] VIU support

### ISSUE THREAD

**Issue by antonio8909** [jaysonlong/webvideo-downloader#71]
Hello

Is it possible to add support for VIU?

Webpage: https://www.viu.com/

Thank you!

**Comment by snowywish** [comment]
and pls viki also

**Comment by chali26** [comment]
我也请求加viki

**Comment by antonio8909** [comment]
@jaysonlong Could you please look into it?

Thanks!

**Comment by jaysonlong** [comment]
no plan to support
