### ISSUE TITLE
i'm not able to iqiyi vip videos anymore & Eng sub didn't re-sync properly.

### ISSUE THREAD

**Issue by snowywish** [jaysonlong/webvideo-downloader#72]
Please help it stop working whenever I tried to download iqiyi VIP videos. And Eng sub didn't re-sync properly.
pls check
https://www.iq.com/play/19rrhasnvx?frmrp=search&frmb=list&frmrs=title

**Comment by jaysonlong** [comment]
I don't have a vip account to test, if you want this problem to be solved, please send an available vip account and its password to my personal email: im.lgchen@foxmail.com
