### ISSUE TITLE
[Common m3u8] Aisplay

### ISSUE THREAD

**Issue by apt42541** [jaysonlong/webvideo-downloader#76]
it m3u8 hls player , common hls downloader script can download ts file 

but problem occur at merge and decrypt.

it say finish at videos folder but no video there

m3u8 script and  headers['referer'] = 'https://web-player.ais-vidnt.com/

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=323360,RESOLUTION=480x270,CODECS="avc1.42e015,mp4a.40.2"
01.m3u8?playbackUrlPrefix=https%3A%2F%2Ftr.play-rbcdn.ais.co.th%3A8438%2F&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Forigin&tt=b55de84cb39a45f927f00ed3540ce238&chunkHttps=true&tmid=ais-dhOvT1-Kakoc&tpbk=yA1scxuK6AVz2uQh&rrt=1622005594&tmod=rfk&rsid=4a730f7f-9064-466c-9b34-bdebfdceb1fd&tuid=lfZYhfF5Gxqf%2B0tjmZ28rj9zvzgGfLxBIeKQH9N9zZY0D%2FauFySpjzjdiUEsNkjIZEQTLYxWNqIVgz3ZzybbJRY3%2Bt35Lj5DQm6z845rvgGbc%3D&cdn=redfox-https&tdid=70e8341314f84ba491e54d1036c07aa2&origin=emc&tfa=f0-fc&tttl=1622091994
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=991136,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2"
02.m3u8?playbackUrlPrefix=https%3A%2F%2Ftr.play-rbcdn.ais.co.th%3A8438%2F&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Forigin&tt=b55de84cb39a45f927f00ed3540ce238&chunkHttps=true&tmid=ais-dhOvT1-Kakoc&tpbk=yA1scxuK6AVz2uQh&rrt=1622005594&tmod=rfk&rsid=4a730f7f-9064-466c-9b34-bdebfdceb1fd&tuid=lfZYhfF5Gxqf%2B0tjmZ28rj9zvzgGfLxBIeKQH9N9zZY0D%2FauFySpjzjdiUEsNkjIZEQTLYxWNqIVgz3ZzybbJRY3%2Bt35Lj5DQm6z845rvgGbc%3D&cdn=redfox-https&tdid=70e8341314f84ba491e54d1036c07aa2&origin=emc&tfa=f0-fc&tttl=1622091994
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1401728,RESOLUTION=854x480,CODECS="avc1.64001e,mp4a.40.2"
03.m3u8?playbackUrlPrefix=https%3A%2F%2Ftr.play-rbcdn.ais.co.th%3A8438%2F&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Forigin&tt=b55de84cb39a45f927f00ed3540ce238&chunkHttps=true&tmid=ais-dhOvT1-Kakoc&tpbk=yA1scxuK6AVz2uQh&rrt=1622005594&tmod=rfk&rsid=4a730f7f-9064-466c-9b34-bdebfdceb1fd&tuid=lfZYhfF5Gxqf%2B0tjmZ28rj9zvzgGfLxBIeKQH9N9zZY0D%2FauFySpjzjdiUEsNkjIZEQTLYxWNqIVgz3ZzybbJRY3%2Bt35Lj5DQm6z845rvgGbc%3D&cdn=redfox-https&tdid=70e8341314f84ba491e54d1036c07aa2&origin=emc&tfa=f0-fc&tttl=1622091994
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3250144,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
04.m3u8?playbackUrlPrefix=https%3A%2F%2Ftr.play-rbcdn.ais.co.th%3A8438%2F&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Forigin&tt=b55de84cb39a45f927f00ed3540ce238&chunkHttps=true&tmid=ais-dhOvT1-Kakoc&tpbk=yA1scxuK6AVz2uQh&rrt=1622005594&tmod=rfk&rsid=4a730f7f-9064-466c-9b34-bdebfdceb1fd&tuid=lfZYhfF5Gxqf%2B0tjmZ28rj9zvzgGfLxBIeKQH9N9zZY0D%2FauFySpjzjdiUEsNkjIZEQTLYxWNqIVgz3ZzybbJRY3%2Bt35Lj5DQm6z845rvgGbc%3D&cdn=redfox-https&tdid=70e8341314f84ba491e54d1036c07aa2&origin=emc&tfa=f0-fc&tttl=1622091994
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5304608,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
05.m3u8?playbackUrlPrefix=https%3A%2F%2Ftr.play-rbcdn.ais.co.th%3A8438%2F&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Forigin&tt=b55de84cb39a45f927f00ed3540ce238&chunkHttps=true&tmid=ais-dhOvT1-Kakoc&tpbk=yA1scxuK6AVz2uQh&rrt=1622005594&tmod=rfk&rsid=4a730f7f-9064-466c-9b34-bdebfdceb1fd&tuid=lfZYhfF5Gxqf%2B0tjmZ28rj9zvzgGfLxBIeKQH9N9zZY0D%2FauFySpjzjdiUEsNkjIZEQTLYxWNqIVgz3ZzybbJRY3%2Bt35Lj5DQm6z845rvgGbc%3D&cdn=redfox-https&tdid=70e8341314f84ba491e54d1036c07aa2&origin=emc&tfa=f0-fc&tttl=1622091994

**Comment by Rule1311** [comment]
Are able to download from AIS PLAY?

**Comment by jaysonlong** [comment]
Any other hls website except for the listed websites are not guaranteed to be downloaded ok

**Comment by akin230** [comment]
https://49-231-37-37-rewriter.ais-vidnt.com/ais/play/anevia/live/eds/W0016/HLS/W0016.m3u8?playbackUrlPrefix=https%3A%2F%2Ftr.http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Fanevia&tt=a04828ac8ce91c1519c938507dae2d78&chunkHttps=true&tmid=W0016&tpbk=HSeSsdi4B0YWJQP9&rrt=1751881691&tmod=rfk&rsid=b9634bac-3c81-4ce3-869e-db2b1cef4669&tuid=cd1d199238&cdn=redfox-https&tdid=832991d1dcef13baa3681c3eb0ab20e2&origin=anevia&tfa=f0-fc&tttl=1751968088

**Comment by akin230** [comment]
`https://49-231-34-109-rewriter.ais-vidnt.com/ais/play/anevia/live/eds/W0016/HLS/W0016.m3u8?playbackUrlPrefix=https%3A%2F%2Fhw.play-rbcdn.ais.co.th&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Fanevia&tt=1012cce10610a371b6ca66a344203d23&chunkHttps=true&tmid=W0016&tpbk=cfHFyAFgc6VTUQ5J&rrt=1753395657&tmod=rfkoh&rsid=78fae31f-93aa-44a1-9ede-21745f3f34ba&tuid=a24fa5fc48&cdn=huawei-https&tdid=84cf5af42a3234d9f2ec0d5270e30cee&origin=anevia&tfa=f0-fc&tttl=1753482057))`

**Comment by akin230** [comment]
https://49-231-34-109-rewriter.ais-vidnt.com/ais/play/anevia/live/eds/W0016/HLS/W0016.m3u8?playbackUrlPrefix=https%3A%2F%2Fhw.play-rbcdn.ais.co.th&originBasicUrl=http%3A%2F%2Fpl-origin.ais-vidnt.com%2Fais%2Fplay%2Fanevia&tt=1012cce10610a371b6ca66a344203d23&chunkHttps=true&tmid=W0016&tpbk=cfHFyAFgc6VTUQ5J&rrt=1753395657&tmod=rfkoh&rsid=78fae31f-93aa-44a1-9ede-21745f3f34ba&tuid=a24fa5fc48&cdn=huawei-https&tdid=84cf5af42a3234d9f2ec0d5270e30cee&origin=anevia&tfa=f0-fc&tttl=1753482057

![Image](https://github.com/user-attachments/assets/033ddc06-e08a-487f-8b29-0757d08bb5cf)
