### ISSUE TITLE
[BUG] MSE视频导出

### ISSUE THREAD

**Issue by apt42541** [jaysonlong/webvideo-downloader#77]
video work fine but audio not correct 

视频是行了但是声音失真  

测试 https://www.bde4.cc/guoju/play/19843-0.htm

**Comment by jaysonlong** [comment]
这个脚本是实验性的，暂无时间维护，如有兴趣可自行研究

**Comment by apt42541** [comment]
视频 480p at wetv , 他行了 但是 1080 不行 。 我不知道原因从哪里。

谢谢 你答案我的Issue
