### ISSUE TITLE
影片合并

### ISSUE THREAD

**Issue by afjpdsf0137** [jaysonlong/webvideo-downloader#79]
部分影片合并后会多出秒数（10~50不等）
并且体现在播放时的轻微卡顿或迟延
我把分片单独下指令合成则正常

**Comment by jaysonlong** [comment]
尝试使用校正时间戳参数： `python daemon.py -c`

**Comment by NevermoreMiss** [comment]
遇到了同样的问题

> 部分影片合并后会多出秒数（10~50不等） 并且体现在播放时的轻微卡顿或迟延 我把分片单独下指令合成则正常

假如自行合并好像也会有视频整体时长不对的情况出现，请问您后续是否解决了这个问题，如解决可否赐教一下，感谢！

**Comment by NevermoreMiss** [comment]
> 尝试使用校正时间戳参数： `python daemon.py -c`

使用此命令同样会出现时长不对的情况

流媒体：台湾iqiyi
视频链接：https://www.iq.com/play/%E6%97%A0%E7%A5%9E%E4%B9%8B%E5%9C%B0%E4%B8%8D%E4%B8%8B%E9%9B%A8-%E7%AC%AC5%E9%9B%86-27t2cq8kj4o?lang=zh_cn&frmrp=home&frmb=focus_banner_1&frmrs=click

恳请查看一下@jaysonlong  可提供VIP账号

**Comment by jaysonlong** [comment]
过久的issue。如果问题依然存在，请提交新issue
