### ISSUE TITLE
Mac OS 显示下载完成，但是videos文件夹里没有视频

### ISSUE THREAD

**Issue by Plovor** [jaysonlong/webvideo-downloader#8]
显示完成了，但是videos文件夹里没有视频是咋回事
<img width="821" alt="截屏2020-09-22 下午8 20 58" src="https://user-images.githubusercontent.com/26405686/93881190-2bd6f300-fd11-11ea-9e67-e7dde4dd00e6.png">

**Comment by Plovor** [comment]
解决了，Python3.7不支持相对路径，下载很好用，感谢😄😸

**Comment by jaysonlong** [comment]
好用可以点个Star😉
