### ISSUE TITLE
Download Subtitle separated from video (not intergrated to video)

### ISSUE THREAD

**Issue by khanguyenwk** [jaysonlong/webvideo-downloader#86]
Hello Jayson Long
I'm very happy with this app, now I can download lots of movies to watch and to learn Chinese
But there's a problem that sometimes I want to extract the subtile from the video. It's not convenient to do that. Can you make an option that we will have the subtile file separated with the video. Then I don't have to extract the subtile from the video anymore.

And we can have both separated subtiles and intergrated subtiles with video (I'm still happy with the intergrated one)

Thank you so much~

**Comment by jaysonlong** [comment]
Just use the debug option, then you will get the separated subtitles and video:
> python daemon.py -d
