### ISSUE TITLE
wetv can't download

### ISSUE THREAD

**Issue by fremzuck** [jaysonlong/webvideo-downloader#88]
I try download https://wetv.vip/play/fte4uy4jar3n8gt/e0039wyro6v after the download is complete, the file size is only 200K.

i try debug m3u8 url and use ffmpeg for download this url ffmpeg return sample-aes encryption.
Some episodes can be loaded normally.
![Screen Shot 2564-07-12 at 07 24 37](https://user-images.githubusercontent.com/71850369/125214618-3be0b300-e2e2-11eb-9d58-ec47a306547d.png)

**Comment by jaysonlong** [comment]
There's no copyright for this episode in my region (China), that I can't know what happened.
