### ISSUE TITLE
iq.com/爱奇艺国际版 显示不了下载的标识了

### ISSUE THREAD

**Issue by ali617768987** [jaysonlong/webvideo-downloader#89]
![微信截图_20210720163125](https://user-images.githubusercontent.com/77323405/126288884-289cc8d6-c046-4038-9d4d-58348c89c9c8.png)

爱奇艺国际版上 那两个插件都装了 也没有显示了下载的标识 好像就今天开始不显示了 

其他上面还正常有，是被爱奇艺屏蔽了吗？ 

还有什么其他方法可以调用出来呢？

**Comment by xyan24** [comment]
一个小时前还有的，现在尝试也消失了

**Comment by khanguyenwk** [comment]
Yeah I have the same issue. Maybe iqiyi just changed their algorithm. I hope you can update the new one to solve this. Because Iqiyi is a really great source of Chinese dramas.

**Comment by fremzuck** [comment]
i have the same problem

**Comment by sohail0098** [comment]
Ajaxhook(?) no longer detects the dash URL from iqiyi. 
Another change is on the iqiyi dash link data. The data is now enclosed in the `try` block and there is a `catch` block at the end. So it cannot be parsed as `resp.json()` directly anymore. What I notice is that almost all the dash links I checked contained the same length of try and catch data and can be sliced at (38, -15) to get the necessary data which can then be parsed as JSON. 

Screencaps:
1) No dash URL detected.
![image](https://user-images.githubusercontent.com/24472929/126595962-75a4a42c-1a26-44ca-bbdc-ee7f66fd6ef5.png)

2) Change in the dash data preventing JSON parsing.
![image](https://user-images.githubusercontent.com/24472929/126596016-3ec5185b-eda6-4370-b0e4-33834d402be5.png)

**Comment by sohail0098** [comment]
It seems like iQIYI has reverted the changes. The things are back to how they were including the data that is received in dash link (without try and catch blocks)

**Comment by fremzuck** [comment]
> Ajaxhook(?) no longer detects the dash URL from iqiyi.
> Another change is on the iqiyi dash link data. The data is now enclosed in the `try` block and there is a `catch` block at the end. So it cannot be parsed as `resp.json()` directly anymore. What I notice is that almost all the dash links I checked contained the same length of try and catch data and can be sliced at (38, -15) to get the necessary data which can then be parsed as JSON.
> 
> Screencaps:
> 
> 1. No dash URL detected.
>    ![image](https://user-images.githubusercontent.com/24472929/126595962-75a4a42c-1a26-44ca-bbdc-ee7f66fd6ef5.png)
> 2. Change in the dash data preventing JSON parsing.
>    ![image](https://user-images.githubusercontent.com/24472929/126596016-3ec5185b-eda6-4370-b0e4-33834d402be5.png)

Can this problem be solved? try is attached to the callback parameter.

**Comment by peedan** [comment]
It works now after updating daemon.py , api.py and WebVideoDownloader.user.js(v.2.2.2) .

**Comment by sohail0098** [comment]
> Can this problem be solved? try is attached to the callback parameter.

The new update seems to have addressed both the issues I mentioned. I didn't really notice the commit when I made the comment on this issue.

**Comment by fremzuck** [comment]
Thank. Work last updated.

**Comment by jaysonlong** [comment]
@sohail0098  That's right, the iqiyi (iq.com) has changed the way the get dash info of video, use the JSONP instead of AJAX. When I hook both JSONP and AJAX, all problems were solved.

People should upgrade to the lastest version to solve it, including violentmonkey scripts and python code.

**Comment by sohail0098** [comment]
@jaysonlong I really appreciate the explanation. Thank You and thanks for the quick fix as well. I made some attempts of my own just for the kicks of learning and I really applaud the effort you put into this tool. 🙌 I really love the modularity of this tool. And thanks to the downloader being written in python (thanks yet again), I can make extensions of my own in it without breaking any other stuff.
