### ISSUE TITLE
CommonHlsDownloader download complete but file not show.

### ISSUE THREAD

**Issue by fremzuck** [jaysonlong/webvideo-downloader#95]
![Screen Shot 2564-08-09 at 17 11 35](https://user-images.githubusercontent.com/71850369/128691171-c5bee2ce-9234-4a2b-b7a9-c3b452681c95.png)

CommonHlsDownloader download hls complete but can't find the file.
CommonHlsDownloader version 2.2.2

**Comment by ali617768987** [comment]
Because downloading VIU is not supported

**Comment by fremzuck** [comment]
> Because downloading VIU is not supported

I tried on all sites that use hls but it doesn't show downloaded files.

**Comment by ortegabae** [comment]
to download on viu.com use the videoder application

**Comment by ali617768987** [comment]
> > Because downloading VIU is not supported
> 
> I tried on all sites that use hls but it doesn't show downloaded files.

These are the HLS that support downloading

![111](https://user-images.githubusercontent.com/77323405/130380305-92806fdc-750e-42e2-99b8-6023c3ce4be7.png)

**Comment by jaysonlong** [comment]
Except for the listed websites, any other hls website are not guaranteed to be download ok
